blank_issues_enabled: true
contact_links:
  - name: GitHub Discussions
    url: https://github.com/svc-bi-concepts/SnowflakeTutorials/discussions
    about: Ask questions and discuss with the community
  - name: Snowflake Official Documentation
    url: https://docs.snowflake.com/
    about: Check the official Snowflake documentation

